import { TranscriptData } from '../types/transcript';

const mockTranscriptData: TranscriptData = {
  videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
  transcript: [
    { id: 0, text: "Introduction", type: "heading" },
    { id: 1, text: "[Music]", type: "sentence", timestamp: "00:00" },
    { id: 2, text: "We're no strangers to love", timestamp: "00:18", type: "sentence" },
    { id: 3, text: "You know the rules and so do I", timestamp: "00:21", type: "sentence" },
    { id: 4, text: "A full commitment's what I'm thinking of", timestamp: "00:26", type: "sentence" },
    { id: 5, text: "You wouldn't get this from any other guy", timestamp: "00:31", type: "sentence" },
    { id: 6, text: "Chorus", type: "heading" },
    { id: 7, text: "I just wanna tell you how I'm feeling", timestamp: "00:35", type: "sentence" },
    { id: 8, text: "Gotta make you understand", timestamp: "00:39", type: "sentence" },
    { id: 9, text: "Never gonna give you up", timestamp: "00:43", type: "sentence" },
    { id: 10, text: "Never gonna let you down", timestamp: "00:45", type: "sentence" },
    { id: 11, text: "Never gonna run around and desert you", timestamp: "00:47", type: "sentence" },
    { id: 12, text: "Never gonna make you cry", timestamp: "00:51", type: "sentence" },
    { id: 13, text: "Never gonna say goodbye", timestamp: "00:53", type: "sentence" },
    { id: 14, text: "Never gonna tell a lie and hurt you", timestamp: "00:56", type: "sentence" },
    { id: 15, text: "Verse 2", type: "heading" },
    { id: 16, text: "We've known each other for so long", timestamp: "01:00", type: "sentence" },
    { id: 17, text: "Your heart's been aching but you're too shy to say it", timestamp: "01:03", type: "sentence" },
    { id: 18, text: "Inside we both know what's been going on", timestamp: "01:08", type: "sentence" },
    { id: 19, text: "We know the game and we're gonna play it", timestamp: "01:12", type: "sentence" },
    { id: 20, text: "And if you ask me how I'm feeling", timestamp: "01:16", type: "sentence" },
    { id: 21, text: "Don't tell me you're too blind to see", timestamp: "01:21", type: "sentence" },
    { id: 22, text: "Chorus", type: "heading" },
    { id: 23, text: "Never gonna give you up", timestamp: "01:24", type: "sentence" },
    { id: 24, text: "Never gonna let you down", timestamp: "01:27", type: "sentence" },
    { id: 25, text: "Never gonna run around and desert you", timestamp: "01:30", type: "sentence" },
    { id: 26, text: "Never gonna make you cry", timestamp: "01:34", type: "sentence" },
    { id: 27, text: "Never gonna say goodbye", timestamp: "01:37", type: "sentence" },
    { id: 28, text: "Never gonna tell a lie and hurt you", timestamp: "01:40", type: "sentence" },
    { id: 29, text: "Never gonna give you up", timestamp: "01:42", type: "sentence" },
    { id: 30, text: "Never gonna let you down", timestamp: "01:44", type: "sentence" },
    { id: 31, text: "Never gonna run around and desert you", timestamp: "01:47", type: "sentence" },
    { id: 32, text: "Never gonna make you cry", timestamp: "01:51", type: "sentence" },
    { id: 33, text: "Never gonna say goodbye", timestamp: "01:53", type: "sentence" },
    { id: 34, text: "Never gonna tell a lie and hurt you", timestamp: "01:55", type: "sentence" },
    { id: 35, text: "Bridge", type: "heading" },
    { id: 36, text: "(Ooh, give you up)", timestamp: "02:01", type: "sentence" },
    { id: 37, text: "(Ooh, give you up)", timestamp: "02:05", type: "sentence" },
    { id: 38, text: "Never gonna give, never gonna give (Give you up)", timestamp: "02:07", type: "sentence" },
    { id: 39, text: "Never gonna give, never gonna give (Give you up)", timestamp: "02:11", type: "sentence" },
    { id: 40, text: "Verse 3", type: "heading" },
    { id: 41, text: "We've known each other for so long", timestamp: "02:15", type: "sentence" },
    { id: 42, text: "Your heart's been aching but you're too shy to say it", timestamp: "02:20", type: "sentence" },
    { id: 43, text: "Inside we both know what's been going on", timestamp: "02:24", type: "sentence" },
    { id: 44, text: "We know the game and we're gonna play it", timestamp: "02:28", type: "sentence" },
    { id: 45, text: "I just wanna tell you how I'm feeling", timestamp: "02:32", type: "sentence" },
    { id: 46, text: "Gotta make you understand", timestamp: "02:37", type: "sentence" },
    { id: 47, text: "Final Chorus", type: "heading" },
    { id: 48, text: "Never gonna give you up", timestamp: "02:41", type: "sentence" },
    { id: 49, text: "Never gonna let you down", timestamp: "02:44", type: "sentence" },
    { id: 50, text: "Never gonna run around and desert you", timestamp: "02:46", type: "sentence" },
    { id: 51, text: "Never gonna make you cry", timestamp: "02:51", type: "sentence" },
    { id: 52, text: "Never gonna say goodbye", timestamp: "02:53", type: "sentence" },
    { id: 53, text: "Never gonna tell a lie and hurt you", timestamp: "02:56", type: "sentence" },
    { id: 54, text: "Never gonna give you up", timestamp: "02:58", type: "sentence" },
    { id: 55, text: "Never gonna let you down", timestamp: "03:00", type: "sentence" },
    { id: 56, text: "Never gonna run around and desert you", timestamp: "03:02", type: "sentence" },
    { id: 57, text: "Never gonna make you cry", timestamp: "03:07", type: "sentence" },
    { id: 58, text: "Never gonna say goodbye", timestamp: "03:09", type: "sentence" },
    { id: 59, text: "Never gonna tell a lie and hurt you", timestamp: "03:11", type: "sentence" },
    { id: 60, text: "Never gonna give you up", timestamp: "03:14", type: "sentence" },
    { id: 61, text: "Never gonna let you down", timestamp: "03:16", type: "sentence" },
    { id: 62, text: "Never gonna run around and desert you", timestamp: "03:19", type: "sentence" },
    { id: 63, text: "Never gonna make you cry", timestamp: "03:23", type: "sentence" },
    { id: 64, text: "Outro", type: "heading" },
    { id: 65, text: "[Music]", timestamp: "03:27", type: "sentence" },
  ]
};
export const getMockTranscriptData = (): Promise<TranscriptData> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(mockTranscriptData);
    }, 500);
  });
};
